WIP More shogun boot support
terrestris/react-geo-baseclient pull request #714
Opened 2021-02-17 13:15 UTC by annarieger

* Add `UserService` and `AppInfoService`
* Enable user logout
* Fix viewport layout
* TBD

2021-02-17 13:21 UTC, weskamm commented on src/Main.css
> +.ant-layout {
i am against having antd layout things in the base-client, please move these to the project

2021-02-17 13:23 UTC, weskamm requested changes
please restore the ProjectMain.css and also the changes to Main.css

Project specifics should all be handled in the project themselves, not in the baseclient

2021-02-18 08:14 UTC, annarieger commented
> please restore the ProjectMain.css and also the changes to Main.css
> 
> Project specifics should all be handled in the project themselves, not in the baseclient

Done with https://github.com/terrestris/react-geo-baseclient/pull/714/commits/6e57abf1b1b81d10f5c0821ebf47c8eaf6dc2f76

2021-02-19 11:20 UTC, weskamm approved these changes
Looks good on first sight. As this contains fundamental changes, please test this with current application integrations (reckl.) and check if the app still starts and behaves correctly when started with shogun2 backend and also with static appcontext.

2021-02-19 13:42 UTC, annarieger commented
> Looks good on first sight. As this contains fundamental changes, please test this with current application integrations (reckl.) and check if the app still starts and behaves correctly when started with shogun2 backend and also with static appcontext.

I checked the static and shogun2-based clients against the changes introduced here, both apps behaves as expected.

2021-02-19 13:42 UTC, merged